### ISSUE TITLE
Options for compression rate and webp

### ISSUE THREAD

**Issue by warudin** [staticallyio/statically-wp#2]
Just started using the statically.io plugin for WordPress. The first experiences are great, thank you so much!

I know the plugin is only just released, so I guess extra features might be coming soon. At the moment I miss options for setting a compression rate and force webp for images. Are these feature considered for a future release?

**Comment by fransallen** [comment]
Hi @warudin,

Thank you for the good question!

- Yes, many features have been planned, hoping to make it available in the first major release.
- Compression rate is available since 0.2 :)
- For webp, it will be served automatically if the browser supports it. Also, I made a few changes to make the system healthier, and force-webp is the one that was eliminated from **cdn.statically.io** for now because I see it is not used much.

However, missing features can be activated on custom requirements by [contacting us](https://statically.io/contact/).
